# This file should only be edited from the template
name: Triggered once, when initialized from template

on:
  push:
    branches:
      - '**'      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: read
  issues: write

jobs:
  build:
    name: "Copy Issues from Template"
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Initial commit') }}
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow disable template.yml
      - run: |
          .github/template/cpissues.sh
          run: gh issue list -s all 
      
