# This file should only be edited from the template
name: Triggered once, when initialized from template

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**'
    if: >
      github.event.commits[0].commit.message =~ /Initial commit/
      # "Initial commit" is the message applied to the first commit created by the "use template" feature
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: read
  issues: write

jobs:
  build:
    name: "Copy Issues from Template"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh workflow disable template.yml
      - run: |
          .github/template/cpissues.sh
          run: gh issue list -s all 
      
