name: Initial commit workflow

on:
  push:
    branches:
      - '**' 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: read
  issues: write

jobs:
  cpissues:
    name: "Initial commit only"
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Initial commit') }}
    steps:       
      - name: "Checkout"
        uses: actions/checkout@v3
        
      - name: "Raise semaphore or quit"
        run: |
          DISABLE_OUTPUT=$(gh workflow disable template.yml 2>&1)
          if echo "$DISABLE_OUTPUT" | grep -q 'HTTP 404'; then
            echo "::error Another job got here first - This room is crowded - I'm outta here!"
            exit 1
          else 
            echo "Workflow successfully disabled"
            echo $DISABLE_OUTPUT
          fi      
          
      - name: "Copying issues over"
        run: .github/template/cpissues.sh
        
      - name: "List the issues copied"
        run: gh issue list -s all
