name: Initial commit workflow

on:
  push:
    branches:
      - '**' 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: read
  issues: write

jobs:
  cpissues:
    name: "Copy Issues from Template"
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Initial commit') }}
    steps:
      - name: "Raise semaphore or quit"
        run: |
          if [ -f /tmp/semaphore.lock ]; then
            echo "Semaphore is raised - another job got here first - bye!"
            exit 1
          else
            echo "$(date +%s)" > /tmp/semaphore.lock
            echo "Raised the semaphore."
          fi          
      - uses: actions/checkout@v3
      - run: eval gh workflow disable template.yml
      - run: |
          .github/template/cpissues.sh
          gh issue list -s all
