name: Initial commit workflow

on:
  push:
    branches:
      - '**' 
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: read
  issues: write

jobs:
  cpissues:
    name: "Initial commit only"
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Initial commit') }}
    steps:       
      - uses: actions/checkout@v3
      - name: "Raise semaphore or quit"
        workflow_commands: |
          if $(gh workflow disable template.yml); then
            echo "Workflow successfully disabled"
          else
             echo "##[error]Another job got here first - This room is crowded - I'm outta here!"
             exit 1
          fi          
      - name: "Copying issues over"
        run: .github/template/cpissues.sh
      - name: "List the issues copied"
        run: gh issue list -s all
